version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directories:
      - /app
      - /api
      - /plugin
      - /server
      - /tools
    schedule:
      interval: weekly
    groups:
      dart:
        patterns: ['*']
  - package-ecosystem: npm
    directories:
      - /docs
      - /servers
    schedule:
      interval: weekly
    groups:
      javascript:
        patterns: ['*']
  - package-ecosystem: cargo
    directory: /plugin/rust
    schedule:
      interval: weekly
    groups:
      rust:
        patterns: ['*']
  - package-ecosystem: bundler
    directory: /app/android
    schedule:
      interval: weekly
