// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build`, `get`, `new`, `schedule_event`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EventDetails`, `StateFieldAccessIter`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `iter`, `len`, `next_back`, `next`, `nth`, `size_hint`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PluginCallback>>
abstract class PluginCallback implements RustOpaqueInterface {
  factory PluginCallback({
    required FutureOr<void> Function(String) onPrint,
    required FutureOr<void> Function(String, bool?) processEvent,
    required FutureOr<void> Function(String, int?) sendEvent,
    required FutureOr<String> Function(StateFieldAccess) stateFieldAccess,
    required FutureOr<String> Function(String?) tableAccess,
    required FutureOr<String> Function() storageRead,
    required FutureOr<void> Function(String) storageWrite,
  }) => RustLib.instance.api.crateApiPluginPluginCallbackNew(
    onPrint: onPrint,
    processEvent: processEvent,
    sendEvent: sendEvent,
    stateFieldAccess: stateFieldAccess,
    tableAccess: tableAccess,
    storageRead: storageRead,
    storageWrite: storageWrite,
  );
}

abstract class RustPlugin {
  Future<void> run();

  Future<EventResult> runEvent({
    required String eventType,
    required String event,
    String? serverEvent,
    required int source,
    required bool cancelled,
    required int target,
  });
}

class EventResult {
  final int target;
  final String? serverEvent;
  final Set<int>? needsUpdate;
  final bool cancelled;
  final List<(String, int)> scheduledEvents;

  const EventResult({
    required this.target,
    this.serverEvent,
    this.needsUpdate,
    required this.cancelled,
    required this.scheduledEvents,
  });

  @override
  int get hashCode =>
      target.hashCode ^
      serverEvent.hashCode ^
      needsUpdate.hashCode ^
      cancelled.hashCode ^
      scheduledEvents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventResult &&
          runtimeType == other.runtimeType &&
          target == other.target &&
          serverEvent == other.serverEvent &&
          needsUpdate == other.needsUpdate &&
          cancelled == other.cancelled &&
          scheduledEvents == other.scheduledEvents;
}

enum StateFieldAccess {
  tableName,
  tables,
  info,
  players,
  teamMembers,
  namespace,
  game,
}
