on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'servers/**'
name: Deploy Server List
jobs:
  build-servers:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: servers
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up pnpm and Node.js
        uses: pnpm/setup@v2.1.0
        with:
          working-directory: docs
          runtime: node@26
          cache: true
          require-lockfile: true
      - name: Build
        run: pnpm build
      - name: Setup SSH Agent
        if: github.ref == 'refs/heads/develop'
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SFTP_KEY }}
      - name: Add SSH Known Hosts
        if: github.ref == 'refs/heads/develop'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy SSR build via rsync
        if: github.ref == 'refs/heads/develop'
        run: |
          rsync -avz --delete ./ ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:/var/www/servers.setonix

      - name: Restart SSR application
        if: github.ref == 'refs/heads/develop'
        run: |
          ssh ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }} << 'EOF'
            export REMOTE_URLS=${{ secrets.REMOTE_URLS }}
            pm2 stop setonix-servers || true
            cd /var/www/servers.setonix
            PORT=${{ secrets.SERVERS_PORT }} pm2 start dist/server/entry.mjs --name setonix-servers --update-env
          EOF
